name: Functional testing

on:
  push:
    branches: [ master ]
  pull_request: {}

jobs:
  build:
    strategy:
      matrix:
        php-versions: ['8.2', '8.3']
        deployer-version: ['7.3', '7.4']
    runs-on: ubuntu-latest
    concurrency: foo

    steps:
      - uses: actions/checkout@v4
        with:
          path: 'git/mittwald-recipe'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, json
          coverage: pcov

      - name: Setup test project with composer
        run: |
          composer init --name mittwald/deployer-recipes-test --type project --repository '{"type":"path","url":"git/mittwald-recipe"}'
          composer require --dev deployer/deployer:~${{ matrix.deployer-version }}
          composer require --dev mittwald/deployer-recipes:dev-${GITHUB_SHA}
          cp git/mittwald-recipe/functionaltest/deploy.php deploy.php

      - name: Run test deployment
        run: |
          ./vendor/bin/dep deploy -vvv
        env:
          MITTWALD_APP_ID: ${{ secrets.MITTWALD_APP_ID }}
          MITTWALD_APP_DOMAIN: ${{ secrets.MITTWALD_APP_DOMAIN }}
          MITTWALD_API_TOKEN: ${{ secrets.MITTWALD_API_TOKEN }}
