name: PHP type checking and unit testing

on:
  push:
    branches: [ master ]
  pull_request: {}

jobs:
  build:
    strategy:
      matrix:
        php-versions: ['8.2', '8.3', '8.4', '8.5']
        deployer-version: ['7.*', '8.*']
        exclude:
          # Deployer 8 requires PHP 8.3+
          - php-versions: '8.2'
            deployer-version: '8.*'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, json
          coverage: pcov

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install Deployer ${{ matrix.deployer-version }}
        run: composer require --dev --with-all-dependencies --no-progress 'deployer/deployer:${{ matrix.deployer-version }}'

      - name: Run type checker
        run: ./vendor/bin/phpstan

      - name: Run unit tests
        run: ./vendor/bin/phpunit
